### ISSUE TITLE
Option/Command Collisions 

### ISSUE THREAD

**Issue by RichFromGalvanize** [XervoIO/commander.js#3]
If you add an option then add a command with the same name, it will overwrite the option and crash the application. It will also crash if you define the command then the option.

``` javascript
commandline
  .option('-t, --test', 'A test option.');

commandline
  .command('test')
  .action(function(){
    //Do Stuff
  });
```

**Comment by lifenautjoe** [comment]
+1 , seems that no one is maintaining this anymore.

**Comment by tzmanics** [comment]
Hi @BusyRich & @thefabulousdev sorry for the big delay in response, we aren't currently maintaining this repo so I'm going to close this issue for now. Once we figure out the next steps for our fork of `commander.js` we'll post an update on the repo.

Thanks for reaching out and feel free to re-open this issue if it's something you would like addressed sooner rather than later.
