### ISSUE TITLE
Command specific options

### ISSUE THREAD

**Issue by RichFromGalvanize** [XervoIO/commander.js#4]
Right now there is not real way to have the same option with two commands do something different. Should have some way to define options on the command level instead of globally across the whole command line.

**Comment by tzmanics** [comment]
Hi @BusyRich & @LionC sorry for the big delay in response, we aren't currently maintaining this repo so I'm going to close this issue for now. Once we figure out the next steps for our fork of `commander.js` we'll post an update on the repo.

Thanks for reaching out and feel free to re-open this issue if it's something you would like addressed sooner rather than later.
