### ISSUE TITLE
Make the choose program synchronous

### ISSUE THREAD

**Issue by DutchessNicole** [XervoIO/commander.js#6]
Right now I'd like to use the program.choose functionality to specify multiple sets of choice options. So far I haven't been able to do so, because simply invoking program.choose twice, while giving both lists, only returns the first list option as the result for both choices. 

Since this program is purely for CLI purposes where async is very annoying to deal with, would it be possible to have a synchronous version of the program.choose function?

**Comment by tzmanics** [comment]
Hi @Nisengo sorry for the big delay in response, we aren't currently maintaining this repo so I'm going to close this issue for now. Once we figure out the next steps for our fork of `commander.js` we'll post an update on the repo.

Thanks for reaching out and feel free to re-open this issue if it's something you would like addressed sooner rather than later.
